# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ea9d1e63316c8bd71040307ca975cb0"
name = "Fifty Seven Picking"
application_url = "https://picking-app-beryl.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_customers,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://picking-app-beryl.vercel.app/api/auth"]
api_version = "2026-01"
